[dependencies.regex]
version = "1.11.1"
[lib]
name = "text_utils_s"
path = "src/lib.rs"
[package]
resolver = "3"
authors = ["Mayak @"]
autobenches = false
autobins = false
autoexamples = false
autotests = true
build = false
categories = ["text-processing", "data-structures"]
description = "Crate for edit array. Example delete duplicate in array. Clear string"
documentation = "https://docs.rs/text_utils_s"
edition = "2024"
keywords = ["regex", "strings", "collections", "unique", "deduplication"]
license = "MIT OR Apache-2.0"
name = "text_utils_s"
readme = "README.md"
repository = "https://github.com/Mayakq/text_utils"
version = "0.1.5"
